print("skriv första nummret")
x = input()
print("skriv andra nummret")
y = input()
print("skriv tredje nummret")
z = input()
x = int(x)
y = int(y)
z = int(z)
print(x+y)
print(x-y)
print(x*y)
print(x/y)